---
abstract: 'Cosine similarity for sets'
author:
  - 'Helmut Wollmersdorfer, <helmut.wollmersdorfer@gmail.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Set-Similarity-CosinePP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Set::Similarity: '0.009'
  perl: '5.006000'
resources:
  bugtracker: https://github.com/wollmers/Set-Similarity-CosinePP/issues
  homepage: https://github.com/wollmers/Set-Similarity-CosinePP
  repository: https://github.com/wollmers/Set-Similarity-CosinePP.git
version: '0.007'
x_contributors:
  - 'Helmut Wollmersdorfer <helmut@wollmersdorfer.at>'
